### ISSUE TITLE
Unable build the application with  --no-tree-shake-icons

### ISSUE THREAD

**Issue by krishnaji-yedlapalli** [shorebirdtech/updater#100]
Using Shore bird I'm able to generate the apk with the below command 

`shorebird release android`

But I want to build my application with  `--no-tree-shake-icons`, using below command it is failing need a solution 

`shorebird release android --target ./lib/main.dart --no-tree-shake-icons`

**Comment by eseidel** [comment]
Please feel free to re-open if it didn't help.

**Comment by lFitzl** [comment]
I would like to add that in Windows, for some reason it didn't work for me `--` and I changed it to `'--'` to make it work (This from cmd)
Example:  `shorebird release android --flavor x '--' --dart-define='APP=x' --no-tree-shake-icons`
