### ISSUE TITLE
App is freezed during download update

### ISSUE THREAD

**Issue by Fudal** [shorebirdtech/updater#109]
In my cubit I have that code:
```dart
emit(AppOnboardingUpdateDownloading());
await shorebirdCodePush.downloadUpdateIfAvailable();
emit(AppOnboardingUpdateDownloaded());
```

My problem is after emit `AppOnboardingUpdateDownloading` state my app is freezed. I don't have any error. 
`CircularProgressIndicator` is also freezed and nothing is change. After force close and reopen app - I have downloaded changes but user has to force close app because my state `AppOnboardingUpdateDownloaded` never happened.

Here is my all method:
```dart
  Future<void> init(BuildContext context) async {
    try {
      final shorebirdCodePush = ShorebirdCodePush();
      final isUpdateAvailable = await shorebirdCodePush.isNewPatchAvailableForDownload();

      if (isUpdateAvailable) {
        emit(AppOnboardingUpdateDownloading());
        await shorebirdCodePush.downloadUpdateIfAvailable();
        emit(AppOnboardingUpdateDownloaded());
      } else {
        await _getConfigValues();
        _updateLocalizely();
        _waitingForUpdates = false;
      }
    } catch (e, s) {
      unawaited(Sentry.captureException(e, stackTrace: s));
    }
  }
```

**Comment by bryanoltman** [comment]
If you replace `await shorebirdCodePush.downloadUpdateIfAvailable();` with `await Future.delayed(Duration(seconds: 1));`, does this still happen? The fact that this is happening after `emit` and not during `shorebirdCodePush.downloadUpdateIfAvailable` makes me think the issue is outside of the code pasted here.

**Comment by Fudal** [comment]
If I replace this line with `await Future.delayed(Duration(seconds: 1));` this doesn't happen. App is freezed only when I have new patch and of course have line `await shorebirdCodePush.downloadUpdateIfAvailable();`

**Comment by bryanoltman** [comment]
Hmm, what are you seeing in the app's logs? The function being executed by `downloadUpdateIfAvailable` is the same as what is executed on app launch, so the logs should be similar to what you see there. `downloadUpdateIfAvailable` runs in a background isolate, which shouldn't cause your app to freeze, although it might take a while to complete if your patch is large and/or you're on a slow network.

**Comment by Fudal** [comment]
In my app's logs I have nothing. I don't have any error or more info

**Comment by bryanoltman** [comment]
Hmm, that doesn't seem right. You don't see something like:

```
2024-01-03 18:37:55.838328+0800 xxx[623:70498] [VERBOSE0:shorebird.cc(151)] Shorebird updater: no active patch.
2024-01-03 18:37:55.838424+0800 xxx[623:70498] [VERBOSE0:shorebird.cc(155)] Starting Shorebird update
[00:00:00.002] (1701cb000) INFO   Sending patch check request: PatchCheckRequest { app_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", channel: "stable", release_version: "1.0.0+1", patch_number: None, platform: "ios", arch: "aarch64" }
```

At any point? Do you have `auto_update` set in your shorebird.yaml?

**Comment by bryanoltman** [comment]
@Fudal just following up on this. Can you create a small test app that reproduces this issue? I haven't been able to get this to happen locally, even with a bad/no network connection.

**Comment by Fudal** [comment]
We can close this issue at least for now. When I will have more information to reproduce this - I'll let you know.

**Comment by orestesgaolin** [comment]
We are trying to pinpoint potential reason for long UI freeze on iOS and after ruling out a lot of other ideas I ended up with this snippet of code. We observe about 10 seconds of total UI freeze. We call `initializeFromRemote` on app coming back to foreground after 30 min of inactivity.

```dart
class AppUpdateCubit extends Cubit<AppUpdateState> {
  AppUpdateCubit()
      : super(
          const AppUpdateState(
            currentPatch: null,
            isUpdateAvailable: false,
            isUpdateReadyToApply: false,
          ),
        ) {
    _initialize();
  }

  final updater = ShorebirdUpdater();
  final Logger log = Logger(tag: 'AppUpdateCubit');

  Future<void> _initialize() async {
    try {
      if (!updater.isAvailable) {
        emit(
          state.copyWith(
            isUpdateAvailable: false,
            isUpdateReadyToApply: false,
          ),
        );
        return;
      }
      final currentPatch = await updater.readCurrentPatch();
      final updateAvailable = await updater.checkForUpdate();

      switch (updateAvailable) {
        case UpdateStatus.upToDate:
          emit(
            state.copyWith(
              currentPatch: currentPatch?.number,
              isUpdateAvailable: false,
              isUpdateReadyToApply: false,
            ),
          );
        case UpdateStatus.outdated:
          emit(
            state.copyWith(
              currentPatch: currentPatch?.number,
              isUpdateAvailable: true,
              isUpdateReadyToApply: false,
            ),
          );
          await updater.update();
          final nextPatch = await updater.readNextPatch();
          if (nextPatch != null) {
            emit(
              state.copyWith(
                currentPatch: currentPatch?.number,
                isUpdateAvailable: true,
                isUpdateReadyToApply: true,
              ),
            );
          }
        case UpdateStatus.restartRequired:
          emit(
            state.copyWith(
              currentPatch: currentPatch?.number,
              isUpdateAvailable: true,
              isUpdateReadyToApply: true,
            ),
          );
        case UpdateStatus.unavailable:
          emit(
            state.copyWith(
              currentPatch: currentPatch?.number,
              isUpdateAvailable: false,
              isUpdateReadyToApply: false,
            ),
          );
      }
    } catch (e, s) {
      if (e is UpdateException) {
        log.e('UpdateException: message: ${e.message} | reason: ${e.reason}');
      } else {
        log.e('Error while checking for update', e, s);
      }
    }
  }

  Future<void> initializeFromRemote() async {
    await Future<void>.delayed(const Duration(seconds: 5));
    await _initialize();
  }
}
```

I wonder if you can see any potential explanation for that to happen? I'm not 100% sure that it's the shorebird that leads to the UI freeze, but we cannot find the reason for the jank elsewhere.

- Flutter 3.29.3
- shorebird_code_push: ^2.0.3
- iOS 18, iPhone 12 Mini
- release build
