### ISSUE TITLE
shorebird release giving an error

### ISSUE THREAD

**Issue by bharathkoli008** [shorebirdtech/updater#112]
PS E:\Nexential\livekart_ui> shorebird release android
✓ Building release (56.7s)
✓ Fetching apps (0.7s)
' (OS Error: The filename, directory name, or volume label syntax is incorrect.ools\adb.exe
, errno = 123) (0.3s)

Also my shorebird doctor gave no errors

**Comment by bharathkoli008** [comment]
Its happening only in my PC

**Comment by eseidel** [comment]
We did a bunch of fixes to finding adb a few weeks ago.  I would be very interested to know if you're able to reproduce with the latest shorebird.  FYI @bryanoltman

**Comment by eseidel** [comment]
Are you able to share the output of `shorebird doctor`?  Thanks!

**Comment by bharathkoli008** [comment]
Ok after upgrading shorebird and flutter it worked thanks
