### ISSUE TITLE
Can't install shorebird cli properly how to fix ?

### ISSUE THREAD

**Issue by aktharOG** [shorebirdtech/updater#122]
PS C:\Users\vpdil\OneDrive\Documents\Work\Mine\Flutter\TDM\tdm_user_app> iwr -UseBasicParsing 'https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1'|iex
>>
>>
Error: Existing Shorebird installation detected. Use --force to overwrite.
PS C:\Users\vpdil\OneDrive\Documents\Work\Mine\Flutter\TDM\tdm_user_app> shorebird
shorebird : The term 'shorebird' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ shorebird
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (shorebird:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\vpdil\OneDrive\Documents\Work\Mine\Flutter\TDM\tdm_user_app>

NOTE :: Firstly when i tried to install the cli it was downloading but suddently my power gone and then i use this it's not working saying 'To Rewrite' So how can Rewrite or force ??

**Comment by eseidel** [comment]
I recommend installing with force, yes.  It looks like Shorebird was installed, but not added to your path. Adding to your path is the last step the installer does, installing again with --force should fix it.  You can also manually add Shorebird to your path.  This is what the script does to add Shorebird to your path:
https://github.com/shorebirdtech/install/blob/main/install.ps1#L49

**Comment by aktharOG** [comment]
Can you share me how I can force install or add path manually

**Comment by eseidel** [comment]
You should be able to pass --force to the install script and it will do a force install.

It's also possible to add $HOME/.shorebird to your path manually, although if the install was interrupted, it's unclear if it completed. I'd probably start by just passing --force to the install script.

**Comment by aktharOG** [comment]
But when I pass the — force the command is not working :



iwr -UseBasicParsing '
https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1'|iex
—force

  Is this not correct ?

**Comment by eseidel** [comment]
@bryanoltman do you recall?

**Comment by bryanoltman** [comment]
Adding --force to that command won't provide the argument to our install script. I'd remove your shorebird directory (.shorebird in your home directory) and try running the install script again.

**Comment by aktharOG** [comment]
Ok, I will try that.

**Comment by saf1234** [comment]
> Can you share me how I can force install or add path manually


TRY THIS
iwr -UseBasicParsing 'https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1' -OutFile install.ps1; .\install.ps1 --force

**Comment by bryanoltman** [comment]
Closing this due to age
