### ISSUE TITLE
feat: downloadUpdateIfAvailable should return success/failure

### ISSUE THREAD

**Issue by lucky1213** [shorebirdtech/updater#123]

**Comment by eseidel** [comment]
Sounds like you would like:
https://pub.dev/documentation/shorebird_code_push/latest/shorebird_code_push/ShorebirdCodePush/downloadUpdateIfAvailable.html
To return some value to indicate that it actually did an install or not, correct?

**Comment by eseidel** [comment]
I suspect the workaround for now would be to call https://pub.dev/documentation/shorebird_code_push/latest/shorebird_code_push/ShorebirdCodePush/isNewPatchReadyToInstall.html right after.

**Comment by luatvudinh** [comment]
> I suspect the workaround for now would be to call https://pub.dev/documentation/shorebird_code_push/latest/shorebird_code_push/ShorebirdCodePush/isNewPatchReadyToInstall.html right after.

Do you have a plan to enhance this flow @eseidel ? We did manual flow but it was not clear enough for case exception occurring. 
At the moment, we were retrying several times before force user to download the latest version.

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/shorebird/issues/123 is also related.

I think we don't yet have a plan as to exactly what to build here.  If you have suggestions (ideally with imaginary code) as to how you'd like this API to work, we'd welcome suggestions.

**Comment by luatvudinh** [comment]
Thanks @eseidel. The issue you mentioned is enough for me.

**Comment by felangel** [comment]
We just released [v2.0.0-dev of `package:shorebird_code_push`](https://pub.dev/packages/shorebird_code_push/versions/2.0.0-dev.2) which should address these issues.

You can learn more about what's new in our [blog post](https://shorebird.dev/blog/shorebird-code-push-v2).

Let us know if there's anything else we missed or you think can be improved, closing this for now 👍
