### ISSUE TITLE
Shorebird Engine not available, using no-op implementation

### ISSUE THREAD

**Issue by Obada2020** [shorebirdtech/updater#133]

**Comment by eseidel** [comment]
This message appears when running with `package:shorebird_code_push` under `flutter run` or from `flutter build`, rather than `shorebird release` and `shorebird preview`.  It's benign and expected.  We could probably improve the message text to say more.

**Comment by bilalmuhammed99** [comment]
that's work for me 

> This message appears when running with `package:shorebird_code_push` under `flutter run` or from `flutter build`, rather than `shorebird release` and `shorebird preview`. It's benign and expected. We could probably improve the message text to say more.
