### ISSUE TITLE
feasibility inquiry

### ISSUE THREAD

**Issue by Thidiyas3d** [shorebirdtech/updater#136]
Excited to hot-reload on production.
However, our existing app has plugins such as
1. flutter_reactive_ble
2. geolocator, etc
i.e packages that include native code.

## Can we integrate Shorebird into our app?

**Comment by eseidel** [comment]
Yes.  Shorebird has no affect on any other plugins or native code.  However Shorebird can only be used to update the Dart portions of your application.  So it would not be advisable to try and change the version of your flutter_reactive_ble, geolocator in an update. If you did you might see a warning like this:
https://docs.shorebird.dev/troubleshooting#unexpected-native-changes

You can change any other part of your app in Dart code of course (which is likely the bulk of your app).

https://docs.shorebird.dev/faq#what-cant-we-use-shorebird-code-push-for

Please don't hesitate to reach out with any other questions.  We're also reachable on discord: https://discord.gg/shorebird
