### ISSUE TITLE
Accessing next_boot_patch() during patch launch marks patch as invalid

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/updater#184]
`PatchManager`'s `next_boot_patch` function validates the patch in the "next boot" slot before returning it to avoid attempting to boot an invalid patch. If a patch is invalid, it will not return that patch (either a previous patch or `None` will be returned instead). One way a patch can be found invalid is if we have a record of attempting to boot from it but no record of successfully booting from it.

This method of validation leaves open a window where a new patch that has started booting but has not yet recorded a successful boot. Calls to `next_boot_patch` during this window will run validation on the booting patch (because it is in the `next_boot_patch` slot) and it will fail validation, causing it to be deleted in the boot process.

**Comment by eseidel** [comment]
Eek!  Presumably it’s possible for customers to hit this via the
shorebird_code_push package?

**Comment by bryanoltman** [comment]
I stumbled onto this because of a change in https://github.com/shorebirdtech/updater/pull/183 (using `next_boot_patch` instead of `latest_seen_patch_number` when constructing a patch check request). It looks like calling `shorebirdCodePush.nextPatchNumber()` as the first line of a Flutter app's `main` does not trigger this (tested on an Android emulator), so I imagine the likelihood of someone hitting this because of `shorebird_code_push` is extremely low if not nil.

**Comment by eseidel** [comment]
Ah. Yeah our current “record successful” runs right after dart successfully
initializes. We should probably run it after we reach main or the first
frame and if we had done that we would have similarly hit this. Thanks.
