### ISSUE TITLE
fix: isNewPatchAvailableForDownload() return always true

### ISSUE THREAD

**Issue by ddty2** [shorebirdtech/updater#204]
I am using Flutter 3.24.0 and not using the automatic update feature(auto_update: false in shorebird.yaml file).
I recently encountered a bug during patching. After completing the patch and restarting the app, the response from `ShorebirdCodePush().isNewPatchAvailableForDownload()` is always `true`.

Below is the preview logs from the staging track.
```
Which release would you like to patch? 1.0.19+20
✓ Fetching aab artifact (0.4s)
✓ Downloading aab (3.9s)
✓ Building patch with Flutter 3.22.3 (9015e1b42a) (65.0s)
✓ Verifying patch can be applied to release (45ms)
✓ Fetching release artifacts (1.1s)
✓ Downloading release artifacts (5.3s)
✓ Creating patch artifacts (19.2s)

🚀 Ready to publish a new patch!

📱 App: xxxxxxx
📦 Release Version: 1.0.19+20
🕹️  Platform: android [arm32 (1.47 MB), arm64 (1.43 MB), x86_64 (1.42 MB)]
🟠 Track: Staging

Would you like to continue? (y/N) Yes
✓ Creating patch (2.3s)
✓ Uploading artifacts (4.8s)
✓ Fetching channels (0.3s)
✓ Promoting patch to staging (0.5s)

✅ Published Patch 5!
xxxxxxxx % shorebird preview --staging --app-id xxxxxxx --release-version 1.0.19+20
✓ Fetching releases (0.5s)
✓ Fetching releases (0.5s)
Which platform would you like to preview?
❯ ◉  iOS
Which platform would you like to preview?
  ◯  iOS
Which platform would you like to preview? Android
✓ Fetching aab artifact (0.3s)
✓ Downloading release (0.3s)
✓ Using staging track (0.9s)
✓ Extracting metadata (0.5s)
✓ Building apks (5.3s)
✓ Installing apks (6.9s)
✓ Starting app (0.5s)
--------- beginning of main
08-09 17:02:19.935 12347 12347 I flutter : updater::cache::updater_state: No existing state file found: File /data/user/0/xxxxxxx/files/shorebird_updater/state.json does not exist, creating new state.
08-09 17:02:19.936 12347 12347 I flutter : [INFO:flutter/shell/common/shorebird/shorebird.cc(166)] Shorebird updater: no active patch.
08-09 17:02:19.936 12347 12347 I flutter : [INFO:flutter/shell/common/shorebird/shorebird.cc(173)] Shorebird auto_update disabled, not checking for updates.

08-09 17:02:21.495 12347 12529 I flutter : updater::network: Sending patch check request: PatchCheckRequest { app_id: "xxxxxxx", channel: "staging", release_version: "1.0.19+20", platform: "android", arch: "aarch64" }

08-09 17:02:21.496 12347 12531 I flutter : updater::network: Sending patch check request: PatchCheckRequest { app_id: "xxxxxxx", channel: "staging", release_version: "1.0.19+20", platform: "android", arch: "aarch64" }

08-09 17:02:25.496 12347 12530 I flutter : updater::network: Sending patch check request: PatchCheckRequest { app_id: "xxxxxxx", channel: "staging", release_version: "1.0.19+20", platform: "android", arch: "aarch64" }

08-09 17:02:25.968 12347 12530 I flutter : updater::updater: Patch check response: PatchCheckResponse { patch_available: true, patch: Some(Patch { number: 5, hash: "0ee36c51220d0404ac68777369d5ded4fcabb0544870fa8f0191e2bc82c40a5a", download_url: "https://artifacts.shorebird.dev/xxxxxxx/android/aarch64/79634/dlc.vmcode", hash_signature: None }), rolled_back_patch_numbers: Some([1]) }
08-09 17:02:25.968 12347 12530 I flutter : updater::updater: Attempting uninstall of patch 1...

08-09 17:02:27.207 12347 12530 I flutter : updater::updater: Patch 5 successfully downloaded. It will be launched when the app next restarts.
08-09 17:02:27.207 12347 12530 I flutter : updater::c_api: Update result: Update installed

08-09 17:02:32.282 12347 12530 I flutter : updater::network: Sending patch check request: PatchCheckRequest { app_id: "xxxxxxx", channel: "staging", release_version: "1.0.19+20", platform: "android", arch: "aarch64" }

08-09 17:02:32.462 12604 12604 I flutter : updater::cache::patch_manager: No public key provided, skipping signature verification
08-09 17:02:32.462 12604 12604 I flutter : [INFO:flutter/shell/common/shorebird/shorebird.cc(147)] Shorebird updater: active path: /data/user/0/xxxxxxx/files/shorebird_updater/patches/5/dlc.vmcode
08-09 17:02:32.462 12604 12604 I flutter : updater::updater: Reporting launch start.
08-09 17:02:32.462 12604 12604 I flutter : updater::cache::patch_manager: No public key provided, skipping signature verification
08-09 17:02:32.463 12604 12604 I flutter : [INFO:flutter/shell/common/shorebird/shorebird.cc(173)] Shorebird auto_update disabled, not checking for updates.

08-09 17:02:32.671 12604 12649 I flutter : checkUpdate - current v5

08-09 17:02:32.671 12604 12720 I flutter : updater::cache::patch_manager: No public key provided, skipping signature verification
08-09 17:02:32.671 12604 12649 I flutter : checkUpdate - next v5
08-09 17:02:32.671 12604 12720 I flutter : updater::network: Sending patch check request: PatchCheckRequest { app_id: "xxxxxxx", channel: "staging", release_version: "1.0.19+20", platform: "android", arch: "aarch64" }
08-09 17:02:32.672 12604 12649 I flutter : checkUpdate - current v5
08-09 17:02:32.672 12604 12722 I flutter : updater::cache::patch_manager: No public key provided, skipping signature verification

08-09 17:02:32.672 12604 12649 I flutter : checkUpdate - next v5
08-09 17:02:32.672 12604 12722 I flutter : updater::network: Sending patch check request: PatchCheckRequest { app_id: "xxxxxxx", channel: "staging", release_version: "1.0.19+20", platform: "android", arch: "aarch64" }

08-09 17:02:33.100 12604 12649 I flutter : checkUpdate - is update available? true

08-09 17:02:33.101 12604 12649 I flutter : checkUpdate - is update available? true
```

**Comment by eseidel** [comment]
Thank you very much for the report.  FYI @bryanoltman

**Comment by eseidel** [comment]
BTW, app_ids don't need to be secret: https://docs.shorebird.dev/faq/#do-i-need-to-keep-my-app_id-secret

**Comment by bryanoltman** [comment]
Hmm, I'm not able to reproduce this in our example app. What I've tried:

1. Create a new Android release
2. Run with `shorebird preview --staging`
3. Click "check for update"
4. See that no patch is available for download
5. Create a staging patch using `shorebird patch android --staging`
6. Click "check for update"
7. See that a new patch is available for download
8. Click "download" to download the patch
9. Click "check for update"
10. See that no new patch is available for download
11. Restart the app
12. See that patch 1 is installed
13. Click "check for update"
14. See that no new patch is available for download

Would you mind sharing reproduction steps?

**Comment by bryanoltman** [comment]
It also doesn't look like you're using Flutter 3.24.0 based on your logs:

`✓ Building patch with Flutter 3.22.3 (9015e1b42a) (65.0s)`

**Comment by ddty2** [comment]
> It also doesn't look like you're using Flutter 3.24.0 based on your logs:
> 
> `✓ Building patch with Flutter 3.22.3 (9015e1b42a) (65.0s)`
> 
> Can you try creating a new release with Flutter 3.24.0 and attempting to reproduce?

This message is the Shorebird release/patch log. I am using is Flutter 3.24.0.

The steps to reproduce are below.
1. Create a new Android release
2. Upload the app bundle to the Play Store(internal test mode).
3. Download and install the app at the Play Store(internal test user).
4. Run and check that no patch is available for download.
5. Create a staging patch using shorebird patch android --staging
6. See that a new patch is available for download
7. Click "download" to download the patch
8. Restart the app
9. See that latest patch is installed("currentPatchNumber == nextPatchNumber is true")
10. See that no new patch is available for download

So, my question is whether we need to check isNewPatchAvailableForDownload() and "currentPatchNumber < nextPatchNumber". And then what should we do in case "nextPatchNumber == null".

**Comment by bryanoltman** [comment]
Can you share your app id?

**Comment by ddty2** [comment]
> Can you share your app id?

oh sorry, "fc8107df-dd1b-401d-b321-df928ae271a5"

**Comment by bryanoltman** [comment]
I'm seeing that the last release for that app with patches is 1.0.19+20, and was built with Flutter 3.22.3. Can you create a new release with 3.24.0 and see if the issue persists?

**Comment by ddty2** [comment]
I am using Flutter 3.24.0. However, when building with Shorebird, it is building with 3.22.3. Is there a way to force it to use version 3.24.0?
If that's not the case, are you suggesting that I should first create a release with version 3.24.0 and then proceed with the patch?
```
xxxx % flutter upgrade
Flutter is already up to date on channel stable
Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 80c2e84975 (12 days ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2
xxxx % shorebird patch android --staging                                                                    
✓ Fetching apps (0.8s)
✓ Fetching releases (0.3s)
Which release would you like to patch?
Which release would you like to patch?
Which release would you like to patch? 1.0.19+20
✓ Fetching aab artifact (0.6s)
✓ Downloading aab (5.0s)
✓ Building patch with Flutter 3.22.3 (9015e1b42a) (82.2s)
✓ Verifying patch can be applied to release (43ms)
✓ Fetching release artifacts (1.0s)
✓ Downloading release artifacts (4.4s)
✓ Creating patch artifacts (16.8s)

🚀 Ready to publish a new patch!

📱 App: paydd (fc8107df-dd1b-401d-b321-df928ae271a5)
📦 Release Version: 1.0.19+20
🕹️  Platform: android [arm32 (1.46 MB), arm64 (1.43 MB), x86_64 (1.41 MB)]
🟠 Track: Staging

Would you like to continue? (y/N) Yes
✓ Creating patch (2.2s)
✓ Uploading artifacts (4.6s)
✓ Fetching channels (0.4s)
✓ Promoting patch to staging (0.4s)

✅ Published Patch 7!
```

**Comment by eseidel** [comment]
Hmm. `shorebird upgrade` should make sure you're on the latest shorebird (which defaults to 3.24.0)

You can also always specify a flutter version with `shorebird release --flutter-version=3.24.0`
https://docs.shorebird.dev/flutter-version/

**Comment by ddty2** [comment]
@eseidel i use latest shorebird and see that defaults value is 3.24.0

```
xxxxx % shorebird flutter versions list
📦 Flutter Versions
✓ 3.24.0
  3.22.3
  3.22.2
  3.22.1
  3.22.0
...
```

**Comment by bryanoltman** [comment]
> If that's not the case, are you suggesting that I should first create a release with version 3.24.0 and then proceed with the patch?

Correct. Releases can only be patched with the version of Flutter used to create them, so you will need to create a new release to use a newer Flutter version.

**Comment by ddty2** [comment]
@bryanoltman Thank you for support. Creating a new release and patch with Flutter 3.24.0 resolved the issue and everything is working fine now.

However, if this issue occurs again, what should be done? Could you explain why this issue occurred? Please let me know what precautions I should take when applying patches. Should I try applying staging patches?

**Comment by eseidel** [comment]
We just made a mistake in a single release which which caused this issue.  We don't currently have a mechanism to mark single releases of Flutter as "bad", which we should have done here to prevent this confusion.

In general, if you were ever to have a problem with Shorebird that we were not able to resolve for you quickly, the solution would be to release a new build of your app (with or without shorebird) via the stores.

Apologies for the trouble, glad that it's resolved now with a new release. Thank you for the report!
