### ISSUE TITLE
feat: package:shorebird_code_push should return more information about update status

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/updater#217]
Right now we only return true/false when checking for an update, and don't explain more about "update already installed" or "no update available" or "we tried to boot from that update and failed", etc.

This would help customers collect analytics about their updates in the field.  Right now they only way to do that is through logs, but they should be able to use the API to get this information.

See also

https://github.com/shorebirdtech/updater/issues/213
https://github.com/shorebirdtech/updater/issues/139
https://github.com/shorebirdtech/updater/issues/123
https://github.com/shorebirdtech/updater/issues/53
https://github.com/shorebirdtech/updater/issues/51

I think it's time for us to do another round of API updates for package:shorebird_code_push.

We can keep the current api signatures and just add versions which return richer information for now.

**Comment by eseidel** [comment]
Related would exposing a richer result to isNewPatchAvailableForDownload, which should tell the caller why it returns false, e.g. that shorebird's servers were unreachable.

**Comment by eseidel** [comment]
I'm not sure if it's best to have an errno value on the updater that's set after each of these calls, or to have some sort of ShorebirdError enum, or what 🤔

**Comment by dragon0629** [comment]
I am very concerned about this. When will it be updated? It is important for users to know what is happening, otherwise they are not sure whether to continue using it.

**Comment by eseidel** [comment]
We don't yet have a timeline for this issue.  We're currently focused on finishing https://github.com/shorebirdtech/shorebird/issues/739

**Comment by felangel** [comment]
We just released [v2.0.0-dev of `package:shorebird_code_push`](https://pub.dev/packages/shorebird_code_push/versions/2.0.0-dev.2) which should address these issues.

You can learn more about what's new in our [blog post](https://shorebird.dev/blog/shorebird-code-push-v2).

Let us know if there's anything else we missed or you think can be improved, closing this for now 👍
