### ISSUE TITLE
fix: add bad build support for iOS

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/updater#29]
It's currently possible to brick an iOS app with a bad patch. This is currently happening with the TestFlight version of TimeShift. Debugging now.

**Comment by eseidel** [comment]
There should be a shorebird_report_bad_patch call, which should be called.  I remember it was in shell.cc or similar?  It was initially gated as android-only, but I thoguht I made it work on iOS too, maybe I never landed that change?

**Comment by eseidel** [comment]
Happy to pair with you on it later.   Make sure you've gclient sync'd before building. :)

Also filed https://github.com/shorebirdtech/shorebird/issues/636 (which is unlikely to be your issue, but is one more tool in our later toolbox for catching local build issues).

**Comment by bryanoltman** [comment]
The build failure was due to me using the wrong gen_snapshot_64

**Comment by bryanoltman** [comment]
It's possible this exists and is working and that the crash I was seeing was due to an issue with our Dart fork

**Comment by eseidel** [comment]
Looks like we already have it:
https://github.com/shorebirdtech/engine/blob/655974aed33b608d1075cffae0fcaf06772d90d8/shell/common/shell.cc#L146
