### ISSUE TITLE
Error with shorebird run

### ISSUE THREAD

**Issue by l00ai** [shorebirdtech/updater#48]
<img width="1500" alt="Screenshot 2023-07-02 at 7 44 48 PM" src="https://github.com/shorebirdtech/updater/assets/74601007/dcc7e045-6dd6-477d-9a74-1503e1e26307">

**Comment by eseidel** [comment]
Hi!  So `6c1f35b941ba46596b88674cbb7c59ac3eff1119` is the git hash for our Flutter Engine fork.  So this is Gradle trying to find those resources.  They're only hosted on https://download.shorebird.dev/ which well tell Flutter's default gradle config to point at via FLUTTER_STORAGE_BASE_URL, (Same mechanism used for proxies, e.g. https://docs.flutter.dev/community/china)

It looks like this is trying to build for Shorebird, but not knowing about that url as a maven source, which flutter.groovy normally adds for you:
https://github.com/flutter/flutter/blob/5328bd9ae0b1c4bf6b4fb24da1909edfa7c7d3a3/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L191

Happy to help debug further, we're reachable on discord: https://discord.gg/shorebird.

**Comment by l00ai** [comment]
Thank you very much 🌸 work perfectly

**Comment by bryanoltman** [comment]
This sounds like https://docs.shorebird.dev/troubleshooting#i-installed-shorebird-and-now-i-cant-run-my-app-in-vs-code. Based on https://github.com/shorebirdtech/updater/issues/48#issuecomment-1621112481, I'm going to close this as fixed.
