### ISSUE TITLE
fix: isNewPatchAvailableForDownload returns false if new patch has been downloaded but not installed

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/updater#53]
While this behavior is technically correct, it is confusing for this to return false if an update has been downloaded but not installed. We should have better documentation around this and/or a more rich return type that indicates that the patch has already been downloaded.

**Comment by eseidel** [comment]
Improved in https://github.com/shorebirdtech/updater/pull/216

**Comment by felangel** [comment]
We just released [v2.0.0-dev of `package:shorebird_code_push`](https://pub.dev/packages/shorebird_code_push/versions/2.0.0-dev.2) which should address these issues.

You can learn more about what's new in our [blog post](https://shorebird.dev/blog/shorebird-code-push-v2).

Let us know if there's anything else we missed or you think can be improved, closing this for now 👍
