### ISSUE TITLE
Better error messaging for hash mismatch errors

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/updater#56]

**Comment by felangel** [comment]
Is this needed anymore? We've added the `shorebird preview` command and deprecated `shorebird run` so it be a lot less likely for folks to encounter this error now.

**Comment by bryanoltman** [comment]
We can maybe punt on it and see how many reports of hash mismatches we get over the week or two after `preview` is released?

**Comment by bryanoltman** [comment]
But yeah, I think if `preview` makes this go away entirely, we don't need to worry about sprucing this up.

**Comment by eseidel** [comment]
I suspect this will happen as part of us cleaning up the rust logging.  Right now rust logs a wall of text when it doesn't need to anymore.

**Comment by eseidel** [comment]
Got another report of this from a customer tonight.
