### ISSUE TITLE
Not able to build web due to dart import ffi.

### ISSUE THREAD

**Issue by harshil-ventura** [shorebirdtech/updater#57]
Im developing a web and mobile app and integrated shorebird code push in mobile app and its working very well. only issue is I'm not able to build web as it throws error of import 'dart:ffi'.

Need solution for this. @eseidel

**Comment by eseidel** [comment]
Felix is working on it as we speak.  We expect to ship this today. https://github.com/shorebirdtech/updater/pull/55
