### ISSUE TITLE
currentPatchNumber returning values much larger than actual patch number

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/updater#85]
There have been several reports in Discord of currentPatchNumber returning very high numbers (10826, 10800) instead of the actual patch number (1 in the second case).

**Comment by eseidel** [comment]
We believe as part of our transition to Redis yesterday we are accidentally returning an internal patch id value instead of the per-release patch number.  We have a fix in progress.

**Comment by bryanoltman** [comment]
Closed by https://github.com/shorebirdtech/_shorebird/pull/346
